apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T06:54:00Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "7110"
  uid: f75bf0df-8f38-4ccc-ab14-c5df390192a6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.109.156.53
  clusterIPs:
  - 10.109.156.53
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32048
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
